name: vanilla-python
services:
  app:
    build:
      context: .
      target: development
      args:
        - WORKDIR=${WORKDIR}
        - VENVPATH=${VENVPATH}
        - USER=${USER}
    env_file: .env