name: flask-blog
services:
  web:
    build:
      context: app
      target: development
    env_file: 
      - .env
      - ./app/.env.dev
    stop_signal: SIGINT
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: 
      context: db
    env_file: 
      - .env
      - ./db/.env.dev
