name: flask-blog
services:
  web:
    build:
      context: ./app
      target: development
    env_file: ./app/.env.dev
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: 
      context: ./db
    # TO DO
    # Need to change to .env
    env_file: ./db/.env.dev