name: flask-blog
services:
  web:
    build:
      context: ./app
      target: development
    env_file: ./app/.env.dev
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: 
      context: ./db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test